# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DFjVGcAotBwDfkpmNWtPTggJC5qCtcYu
"""

# app.py

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

st.title("🎬 Netflix Movies and TV Shows Analysis")

# Load data
@st.cache_data
def load_data():
    df = pd.read_csv("netflix_titles.csv")
    return df

df = load_data()
st.subheader("📊 Dataset Overview")
st.write(df.head())

# Basic info
st.write(f"Total Entries: {df.shape[0]}")
st.write(f"Total Columns: {df.shape[1]}")

# Data Cleaning
df['date_added'] = pd.to_datetime(df['date_added'])
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month

# Dropdown for analysis
option = st.selectbox("Choose Analysis Type:", [
    "Movies vs TV Shows",
    "Top Countries",
    "Content Added Over Years",
    "Ratings Distribution",
    "Top Directors"
])

# 1. Movies vs TV Shows
if option == "Movies vs TV Shows":
    count_type = df['type'].value_counts()
    fig, ax = plt.subplots()
    sns.barplot(x=count_type.index, y=count_type.values, ax=ax)
    ax.set_title("Movies vs TV Shows on Netflix")
    st.pyplot(fig)

# 2. Top Countries
elif option == "Top Countries":
    country_count = df['country'].dropna().apply(lambda x: x.split(",")[0]).value_counts().head(10)
    fig, ax = plt.subplots()
    sns.barplot(y=country_count.index, x=country_count.values, ax=ax)
    ax.set_title("Top 10 Countries with Most Content")
    st.pyplot(fig)

# 3. Content Added Over Years
elif option == "Content Added Over Years":
    added_per_year = df['year_added'].value_counts().sort_index()
    fig, ax = plt.subplots()
    sns.lineplot(x=added_per_year.index, y=added_per_year.values, ax=ax, marker="o")
    ax.set_title("Content Added Over the Years")
    st.pyplot(fig)

# 4. Ratings Distribution
elif option == "Ratings Distribution":
    ratings = df['rating'].value_counts().head(10)
    fig, ax = plt.subplots()
    sns.barplot(y=ratings.index, x=ratings.values, ax=ax)
    ax.set_title("Most Common Ratings on Netflix")
    st.pyplot(fig)

# 5. Top Directors
elif option == "Top Directors":
    top_directors = df['director'].dropna().value_counts().head(10)
    fig, ax = plt.subplots()
    sns.barplot(y=top_directors.index, x=top_directors.values, ax=ax)
    ax.set_title("Top 10 Directors on Netflix")
    st.pyplot(fig)

st.markdown("---")