# -*- coding: utf-8 -*-
"""app1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DFjVGcAotBwDfkpmNWtPTggJC5qCtcYu
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
df = pd.read_csv("netflix_titles.csv")
df['date_added'] = pd.to_datetime(df['date_added'])
df['year_added'] = df['date_added'].dt.year

st.title("📺 Netflix Movies and TV Shows Analysis")

# Chart 1: Movie vs TV Show Count
st.subheader("1️⃣ Distribution of Content Type")
type_count = df['type'].value_counts()
st.bar_chart(type_count)

# Chart 2: Top 10 Countries with Most Titles
st.subheader("2️⃣ Top 10 Countries with Most Content")
country_data = df['country'].value_counts().head(10)
st.bar_chart(country_data)

# Chart 3: Content Added Per Year
st.subheader("3️⃣ Content Added per Year")
year_count = df['year_added'].value_counts().sort_index()
st.line_chart(year_count)

# Chart 4: Top 10 Genres
st.subheader("4️⃣ Most Popular Genres")
genre_data = df['listed_in'].str.split(',').explode().value_counts().head(10)
st.bar_chart(genre_data)

# Chart 5: Ratings Distribution
st.subheader("5️⃣ Distribution of Ratings")
rating_data = df['rating'].value_counts()
fig, ax = plt.subplots()
sns.barplot(x=rating_data.index, y=rating_data.values, ax=ax)
plt.xticks(rotation=45)
st.pyplot(fig)