# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DFjVGcAotBwDfkpmNWtPTggJC5qCtcYu
"""

# app.py

import streamlit as st
import pandas as pd

# ------------------------------------
# Page Setup
# ------------------------------------
st.set_page_config(page_title="Netflix Data Explorer", page_icon="🎬", layout="wide")
st.title("🎬 Netflix Movies and TV Shows Data Explorer")

# ------------------------------------
# Load Dataset
# ------------------------------------
@st.cache_data
def load_data():
    df = pd.read_csv("netflix_titles.csv")
    df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
    df['year_added'] = df['date_added'].dt.year
    df['month_added'] = df['date_added'].dt.month
    return df

df = load_data()

# ------------------------------------
# Sidebar
# ------------------------------------
st.sidebar.header("Navigation")
page = st.sidebar.radio("Go to", [
    "Dataset Overview",
    "Filter Data",
    "Summary Information"
])

# ------------------------------------
# Dataset Overview
# ------------------------------------
if page == "Dataset Overview":
    st.subheader("📘 Netflix Dataset Preview")
    st.write("Here’s a quick look at the dataset before creating visualizations in Tableau.")
    st.dataframe(df.head(10))
    st.write(f"Total Entries: **{df.shape[0]}**")
    st.write(f"Total Columns: **{df.shape[1]}**")

# ------------------------------------
# Filter Data
# ------------------------------------
elif page == "Filter Data":
    st.subheader("🔍 Filter and Explore Data")

    type_filter = st.multiselect("Select Type", options=df["type"].dropna().unique(), default=df["type"].dropna().unique())
    country_filter = st.multiselect("Select Country", options=df["country"].dropna().unique()[:50])
    year_filter = st.slider("Select Year Added", int(df["year_added"].min()), int(df["year_added"].max()), (2015, 2021))

    filtered_df = df[
        (df["type"].isin(type_filter)) &
        (df["year_added"].between(year_filter[0], year_filter[1]))
    ]

    if country_filter:
        filtered_df = filtered_df[filtered_df["country"].isin(country_filter)]

    st.write(f"Showing **{len(filtered_df)}** records based on your filters.")
    st.dataframe(filtered_df)

    csv = filtered_df.to_csv(index=False).encode('utf-8')
    st.download_button("📥 Download Filtered Data (CSV)", data=csv, file_name="filtered_netflix_data.csv", mime="text/csv")

# ------------------------------------
# Summary Information
# ------------------------------------
elif page == "Summary Information":
    st.subheader("📊 Summary Statistics")

    st.write("**Column Information:**")
    st.write(df.describe(include='all'))

    st.write("**Number of Missing Values:**")
    st.write(df.isnull().sum())

    st.write("**Unique Value Counts:**")
    st.write(df.nunique())

st.markdown("---")
st.markdown("💡 Clean and explore data here, then visualize in Tableau.")